"""
PowerTrack Authentication Module
================================

Unified authentication handling for PowerTrack API scripts.
Handles environment variable loading, auth refresh from fetch files, and validation.

Usage:
    from powertrack.auth import load_env, update_auth_from_fetch

    # Load current auth
    auth = load_env()

    # Refresh auth from mostRecentFetch.js (if available)
    update_auth_from_fetch()

    # Use in API calls
    response = requests.get(url, headers={
        'cookie': auth['cookie'],
        'ae_s': auth['ae_s'],
        'ae_v': auth['ae_v']
    })
"""

import os
from pathlib import Path
from typing import Dict, Any, Optional
from urllib.parse import urlparse


def parse_fetch_js(fetch_content: str) -> Dict[str, str]:
    """
    Parse Chrome DevTools fetch (Node.js) content to extract headers.

    Args:
        fetch_content: Raw fetch JavaScript code from Chrome DevTools

    Returns:
        Dict containing parsed headers (cookie, ae_s, ae_v, etc.)

    Raises:
        ValueError: If required headers cannot be found
    """
    headers = {}

    # Extract cookie
    cookie_start = fetch_content.find('"cookie": "')
    if cookie_start != -1:
        cookie_start += 11  # length of '"cookie": "'
        cookie_end = fetch_content.find('"', cookie_start)
        if cookie_end != -1:
            headers['cookie'] = fetch_content[cookie_start:cookie_end]

    # Extract ae_s
    ae_s_start = fetch_content.find('"ae_s": "')
    if ae_s_start != -1:
        ae_s_start += 9  # length of '"ae_s": "'
        ae_s_end = fetch_content.find('"', ae_s_start)
        if ae_s_end != -1:
            headers['ae_s'] = fetch_content[ae_s_start:ae_s_end]

    # Extract ae_v
    ae_v_start = fetch_content.find('"ae_v": "')
    if ae_v_start != -1:
        ae_v_start += 9  # length of '"ae_v": "'
        ae_v_end = fetch_content.find('"', ae_v_start)
        if ae_v_end != -1:
            headers['ae_v'] = fetch_content[ae_v_start:ae_v_end]

    # Extract referer
    referer_start = fetch_content.find('"referer": "')
    if referer_start != -1:
        referer_start += 12  # length of '"referer": "'
        referer_end = fetch_content.find('"', referer_start)
        if referer_end != -1:
            headers['referer'] = fetch_content[referer_start:referer_end]

    # Validate required headers
    required = ['cookie', 'ae_s', 'ae_v']
    missing = [key for key in required if key not in headers or not headers[key]]
    if missing:
        raise ValueError(f"Missing required headers: {', '.join(missing)}")

    return headers


def update_env_file(headers: Dict[str, str], env_file: str = '.env') -> None:
    """
    Update .env file with new authentication headers.

    Args:
        headers: Dict containing cookie, ae_s, ae_v, etc.
        env_file: Path to .env file (default: '.env')
    """
    env_path = Path(env_file)

    # Read existing .env content
    existing_vars = {}
    if env_path.exists():
        with open(env_path, 'r', encoding='utf-8') as f:
            for line in f:
                line = line.strip()
                if line and not line.startswith('#') and '=' in line:
                    key, value = line.split('=', 1)
                    existing_vars[key.strip()] = value.strip('"').strip("'")

    # Update with new values
    existing_vars.update({
        'COOKIE': headers.get('cookie', ''),
        'AE_S': headers.get('ae_s', ''),
        'AE_V': headers.get('ae_v', ''),
        'REFERER': headers.get('referer', ''),
        'BASE_URL': existing_vars.get('BASE_URL', 'https://apps.alsoenergy.com')
    })

    # Write back to .env file
    with open(env_path, 'w', encoding='utf-8') as f:
        f.write("# PowerTrack Authentication Variables\n")
        f.write("# Auto-generated by powertrack.auth.update_auth_from_fetch()\n")
        f.write("# DO NOT commit this file to version control\n\n")
        for key, value in existing_vars.items():
            f.write(f'{key}="{value}"\n')


def update_auth_from_fetch(fetch_file: str = 'auth/mostRecentFetch.js') -> bool:
    """
    Check for mostRecentFetch.js and update .env with fresh authentication.

    Args:
        fetch_file: Path to fetch file (default: 'auth/mostRecentFetch.js')

    Returns:
        True if auth was updated, False if no fetch file found
    """
    fetch_path = Path(fetch_file)

    if not fetch_path.exists():
        print("⚠️  No fetch file found - using existing authentication from .env")
        return False

    try:
        with open(fetch_path, 'r', encoding='utf-8') as f:
            fetch_content = f.read()

        headers = parse_fetch_js(fetch_content)
        update_env_file(headers)

        print("✅ Authentication updated from fetch file")
        return True

    except Exception as e:
        print(f"❌ Failed to update auth from {fetch_file}: {e}")
        return False


def load_env() -> Dict[str, Any]:
    """
    Load environment variables from .env file.

    Returns:
        Dict containing authentication and configuration variables:
        - cookie: Full cookie string
        - ae_s: Security header
        - ae_v: API version
        - base_url: API base URL
        - referer: Default referer URL
    """
    # Try to load from .env file first (python-dotenv style)
    try:
        import dotenv
        dotenv.load_dotenv()
    except ImportError:
        # Manual .env loading if dotenv not available
        env_path = Path('.env')
        if env_path.exists():
            with open(env_path, 'r', encoding='utf-8') as f:
                for line in f:
                    line = line.strip()
                    if line and not line.startswith('#') and '=' in line:
                        key, value = line.split('=', 1)
                        os.environ[key.strip()] = value.strip('"').strip("'")

    return {
        'cookie': os.environ.get('COOKIE', ''),
        'ae_s': os.environ.get('AE_S', ''),
        'ae_v': os.environ.get('AE_V', '086665'),
        'base_url': os.environ.get('BASE_URL', 'https://apps.alsoenergy.com'),
        'referer': os.environ.get('REFERER', 'https://apps.alsoenergy.com/powertrack')
    }


def validate_auth(auth_vars: Dict[str, Any]) -> bool:
    """
    Validate that authentication variables are present and non-empty.

    Args:
        auth_vars: Dict from load_env()

    Returns:
        True if auth is valid, False otherwise
    """
    required = ['cookie', 'ae_s', 'ae_v']
    missing = [key for key in required if not auth_vars.get(key)]

    if missing:
        print(f"❌ Missing authentication variables: {', '.join(missing)}")
        return False

    return True


def get_auth_headers(auth_vars: Dict[str, Any], referer: Optional[str] = None) -> Dict[str, str]:
    """
    Build standard authentication headers for API requests.

    Args:
        auth_vars: Dict from load_env()
        referer: Custom referer URL (optional)

    Returns:
        Dict of headers for requests
    """
    headers = {
        'accept': 'application/json',
        'cookie': auth_vars['cookie'],
        'ae_s': auth_vars['ae_s'],
        'ae_v': auth_vars['ae_v'],
        'user-agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36'
    }

    if referer or auth_vars.get('referer'):
        headers['referer'] = referer or auth_vars['referer']

    return headers